
language: cpp


matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - valgrind
            - bison
            - flex
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-11
            - valgrind
            - bison
            - flex
      env:
        - MATRIX_EVAL="CC=gcc-11 && CXX=g++-11"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-13
          packages:
            - clang-13
            - valgrind
            - bison
            - flex
      env:
        - MATRIX_EVAL="CC=clang-13 && CXX=clang++-13"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # bi build with flex/bison files checked into repo
  - make -j4
  - make test
  - make test_example

  # build flex/bison files in CI
  - make cleanall
  - make -j4
  - make test
  - make test_example

